### ISSUE TITLE
Not working with PyScaffold 3.1 on Python 3.7.0 under Windows 10

### ISSUE THREAD

**Issue by vuolter** [pyscaffold/pyscaffoldext-markdown#2]
```
C:\>putup test -v --markdown
    activate  pyscaffoldext.markdown.extension
      invoke  pyscaffold.api:get_default_options
      invoke  pyscaffold.api:verify_options_consistency
      invoke  pyscaffold.structure:define_structure
      invoke  pyscaffoldext.markdown.extension:markdown
Traceback (most recent call last):
  File "c:\program files\python\3.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python\3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python\3.7\Scripts\putup.exe\__main__.py", line 9, in <module>
  File "c:\program files\python\3.7\lib\site-packages\pyscaffold\shell.py", line 71, in func_wrapper
    func(*args, **kwargs)
  File "c:\program files\python\3.7\lib\site-packages\pyscaffold\utils.py", line 140, in func_wrapper
    func(*args, **kwargs)
  File "c:\program files\python\3.7\lib\site-packages\pyscaffold\cli.py", line 207, in run
    main(sys.argv[1:])
  File "c:\program files\python\3.7\lib\site-packages\pyscaffold\cli.py", line 200, in main
    opts['command'](opts)
  File "c:\program files\python\3.7\lib\site-packages\pyscaffold\cli.py", line 171, in run_scaffold
    api.create_project(opts)
  File "c:\program files\python\3.7\lib\site-packages\pyscaffold\api\__init__.py", line 326, in create_project
    actions, (struct, opts))
  File "c:\program files\python\3.7\lib\site-packages\pyscaffold\api\__init__.py", line 325, in <lambda>
    struct, opts = reduce(lambda acc, f: invoke_action(f, *acc),
  File "c:\program files\python\3.7\lib\site-packages\pyscaffold\update.py", line 122, in invoke_action
    struct, opts = action(struct, opts)
  File "c:\program files\python\3.7\lib\site-packages\pyscaffoldext\markdown\extension.py", line 120, in markdown
    struct = helpers.modify(struct, file_path, self.add_sphinx_md)
  File "c:\program files\python\3.7\lib\site-packages\pyscaffold\api\helpers.py", line 90, in modify
    new_value = (modifier(old_value[0]), update_rule)
  File "c:\program files\python\3.7\lib\site-packages\pyscaffoldext\markdown\extension.py", line 73, in add_sphinx_md
    if line.startswith('source_suffix =')][0]
IndexError: list index out of range

```

**Comment by FlorianWilhelm** [comment]
Thanks @vuolter  for letting us know about that issue. I cannot reproduce it with Python 3.7 under MacOS so maybe the string handling works here different under Windows. Could you post the content of `test/docs/conf.py` after you have done `putup test -v`?

**Comment by FlorianWilhelm** [comment]
Okay, I have it fixed and it runs on my Windows machine. Could you please check it out and close this issue if it also works fine for you. Thanks.

**Comment by vuolter** [comment]
Yeah, here all working fine now. Thanks man! 😃
