### ISSUE TITLE
markdown extension not compatible on Windows due to lack of POSIX symlinks

### ISSUE THREAD

**Issue by sgbaird** [pyscaffold/pyscaffoldext-markdown#45]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
(xtal2png) PS C:\Users\sterg\Documents\GitHub\sparks-baird\xtal2png> conda install -c conda-forge pyscaffoldext-markdown     
(xtal2png) PS C:\Users\sterg\Documents\GitHub\sparks-baird> putup xtal2png --update --force --markdown
```

**Please provide the full traceback.**
```python
(xtal2png) PS C:\Users\sterg\Documents\GitHub\sparks-baird> putup xtal2png --update --force --markdown
Traceback (most recent call last):
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffoldext\markdown\extension.py", line 200, in _symlink
    os.symlink(os.path.relpath(original_file, path.parent), path)
OSError: [WinError 1314] A required privilege is not held by the client: '..\\README.md' -> 'xtal2png\\docs\\readme.md'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\Scripts\putup-script.py", line 9, in <module>
    sys.exit(run())
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffold\shell.py", line 133, in func_wrapper
    func(*args, **kwargs)
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffold\exceptions.py", line 34, in func_wrapper
    func(*args, **kwargs)
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffold\cli.py", line 263, in run
    main(args or sys.argv[1:])
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffold\cli.py", line 256, in main
    opts["command"](opts)
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffold\cli.py", line 225, in run_scaffold
    api.create_project(opts)
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffold\api.py", line 156, in create_project
    return reduce(actions.invoke, pipeline, ({}, opts))
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffold\actions.py", line 99, in invoke
    return action(*struct_and_opts)
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffold\structure.py", line 205, in create_structure
    changed[name], _ = create_structure(node, opts, prefix=path)
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffold\structure.py", line 208, in create_structure
    if file_op(path, content, opts):
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffold\operations.py", line 127, in _no_overwrite
    return file_op(path, contents, opts)
  File "C:\Users\sterg\Miniconda3\envs\xtal2png\lib\site-packages\pyscaffoldext\markdown\extension.py", line 203, in _symlink        
    raise SymlinkError(path, original_file) from ex
pyscaffoldext.markdown.extension.SymlinkError:     Impossible to create a symbolic link {xtal2png\docs\readme.md => xtal2png\README.md}.
    If you are using a non-POSIX operating system, please make sure that your user have
    the correct rights and that your system is correctly configured.

    Please check the following references:
    http://github.com/git-for-windows/git/wiki/Symbolic-Links
    https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/
    https://docs.microsoft.com/en-us/windows/win32/fileio/creating-symbolic-links```
```

**Please provide any additional information below.**
Just came across https://github.com/pyscaffold/pyscaffoldext-dsproject/issues/34 via a Google Search.

## Versions and main components

* PyScaffold Version: 4.2.1
* Python Version: 3.9.12
* Operating system: Windows 10
* How did you install PyScaffold: (**conda**/pip)

**Comment by sgbaird** [comment]
`pip install git+https://github.com/pyscaffold/pyscaffoldext-markdown.git@master` did the trick for me, based on what was mentioned in https://github.com/pyscaffold/pyscaffoldext-dsproject/issues/34

**Comment by abravalheri** [comment]
Thanks for pointing this out @sgbaird, it might be the case we forgot to release the latest version of this extension. Once Florian is back from his holidays we may check if something is missing...
